### ISSUE TITLE
Rename twig functions

### ISSUE THREAD

**Issue by igormukhingmailcom** [Setono/TagBagBundle#2]
Suggest rename twig functions like `head` to `setono_tagbag_tag` (prepend all twig functions with `setono_tagbag_`).

Otherwise, they potentially can conflict with twig functions from other plugins in the future.

**Comment by loevgaard** [comment]
That's probably good practice I guess. Looks so ugly though :D

**Comment by igormukhingmailcom** [comment]
> Looks so ugly though :D

Yeah, but much easier to search in code (search for `head` keyword give you 100+ matches for example) and no chance to conflict with any other lib/bundle/plugin.
